version: '3'

services:
  db:
    image: postgres:16.3-bullseye
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}

      
volumes:
  postgres:
    external: false
  
   